/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;

/**
 *
 * @author Asus
 */
public class DashboardSiswa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardSiswa.class.getName());

    /**
     * Creates new form DashboardSiswa
     */
    public DashboardSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNama = new javax.swing.JLabel();
        btnLihatJadwal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNama.setText("Selamat Dadtang");

        btnLihatJadwal.setText("Lihat Jadwal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblNama))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnLihatJadwal)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNama)
                .addGap(92, 92, 92)
                .addComponent(btnLihatJadwal)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private int userId;
    private String nama;
    private int kelasId;
    private int jurusanId;

    public DashboardSiswa(int userId, String nama, int kelasId, int jurusanId) {
        this.userId = userId;
        this.nama = nama;
        this.kelasId = kelasId;
        this.jurusanId = jurusanId;

        initComponents();
        setLocationRelativeTo(null);

        // Tambahkan tombol
        JButton btnLihatJadwal = new JButton("Lihat Jadwal");
        btnLihatJadwal.addActionListener(e -> tampilkanJadwal());

        // Misalnya ditambahkan ke content pane
        this.getContentPane().add(btnLihatJadwal, BorderLayout.NORTH);
    }

    private void tampilkanJadwal() {
        // Buat frame atau dialog khusus untuk menampilkan tabel jadwal
        JDialog dialog = new JDialog(this, "Jadwal Pelajaran", true);
        dialog.setSize(600, 400);
        dialog.setLocationRelativeTo(this);

        JTable tableJadwal = new JTable();
        JScrollPane scrollPane = new JScrollPane(tableJadwal);
        dialog.add(scrollPane);

        // Load data jadwal
        loadJadwalKelas(tableJadwal);

        dialog.setVisible(true);
    }

    private void loadJadwalKelas(JTable tableJadwal) {
        try {
            Connection conn = config.DatabaseConnection.getConnection();
            String sql = "SELECT p.nama_pelajaran, g.nama_guru, j.hari, j.jam_mulai, j.jam_selesai " +
                         "FROM jadwal j " +
                         "JOIN pelajaran p ON j.pelajaran_id = p.id " +
                         "JOIN guru g ON j.guru_id = g.id " +
                         "WHERE j.kelas_id=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, kelasId);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Pelajaran", "Guru", "Hari", "Jam Mulai", "Jam Selesai"}, 0
            );

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama_pelajaran"),
                    rs.getString("nama_guru"),
                    rs.getString("hari"),
                    rs.getString("jam_mulai"),
                    rs.getString("jam_selesai")
                });
            }

            tableJadwal.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat jadwal: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardSiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatJadwal;
    private javax.swing.JLabel lblNama;
    // End of variables declaration//GEN-END:variables
}
